### PR TITLE
Remove the undefined cases of the array props of TransientState

### PR DESCRIPTION
**Pull request by googol**

### CODE REVIEW

**Comment by raimohanska** [comment]
The lazy initialization is for purpose: premature optimization. Mount/unMount hooks are used extremely rarely so I don't want to waste any memory on them. Also on line 45 the handleMounts controller is created only if one of these arrays exist so that check would have to be changed to `.length>0`.

**Comment by googol** [comment]
Yeah I expected it was an optimization like that. It just seemed ugly so I thought to suggest this.

The line 45 init should not be a problem, since an empty array is falsy, so just like with undefined we won't wnter that branch

**Comment by jussisaurio** [comment]
Actually an empty array is truthy in JS, unlike in Python for example.

**Comment by googol** [comment]
closing in favor of https://github.com/raimohanska/harmaja/pull/66

**Pull request closed without merging**
